# Generated by Django 2.1.1 on 2018-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_auto_20181021_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='numero',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
