# Generated by Django 2.1.1 on 2018-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_auto_20181021_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='date',
            field=models.DateField(verbose_name='Date de parution (AAAA-MM-JJ)'),
        ),
    ]
